version: '3.8'

name: x
services:
  postgres:
    container_name: x-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "${DOCKER_POSTGRES_DB}"
      POSTGRES_USER: "${DOCKER_DOCKER_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${DOCKER_POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
  redis:
    container_name: x-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
